language: java
jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - "./gradlew build"
  - "./gradlew codeCoverageReport || echo 'code coverage upload failed'"

env:
  global:
    - CODACY_PROJECT_TOKEN=e9c07f97fad84186826f873f384a6112

after_success:
  - "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"
