vault_section = "preprod"
#idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
idam_api_url = "http://idam-api-idam-aat.service.core-compute-aat.internal"
capacity = "2"
frontend_url = "https://www-ccd.nonprod.platform.hmcts.net"
