vault_section = "preprod"
#idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
capacity = "2"
frontend_url = "https://www-ccd.nonprod.platform.hmcts.net"
