idam_api_url = "https://idam-api.platform.hmcts.net"
capacity = "2"
frontend_url = "https://www.ccd.platform.hmcts.net"
asp_name = "ccd-definition-store-api-prod"
asp_rg = "ccd-definition-store-api-prod"
