idam_api_url = "http://idam-api-idam-saat.service.core-compute-idam-saat.internal"
asp_name = "ccd-definition-store-api-saat"
asp_rg = "ccd-definition-store-api-saat"
elastic_search_enabled = "false"
elastic_search_fail_on_import = "true"
elastic_search_dynamc = "strict"
