java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DEFINITION_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
    DEFINITION_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    DEFINITION_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    DEFINITION_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DEFINITION_STORE_DB_OPTIONS: "?sslmode=require"
    DEFINITION_STORE_DB_MAX_POOL_SIZE: 5

    ENABLE_DB_MIGRATE: true
    postgresql:
      enabled: true
