java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 2048Mi
  devcpuRequests: 2000m
  devmemoryLimits: 4096Mi
  devcpuLimits: 4000m
  environment:
    DEFINITION_STORE_DB_NAME: ccd_definition_store
    DEFINITION_STORE_DB_HOST: ccd-definition-store-api-postgres-db-v11-aat.postgres.database.azure.com
