DROP TABLE IF EXISTS public.reindex CASCADE;

--
-- Name: reindex; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.reindex (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reindex                  BOOLEAN NOT NULL,
    delete_old_index         BOOLEAN NOT NULL,
    index_name               VARCHAR(200) NOT NULL,
    start_time               TIMESTAMP NOT NULL,
    end_time                 TIMESTAMP NOT NULL,
    status                   VARCHAR(50) NOT NULL,
    case_type_reference      VARCHAR(70),
    jurisdiction             VARCHAR(70) NOT NULL,
    message                  TEXT
);