ALTER TABLE ONLY PUBLIC.SHELL_MAPPING ADD CONSTRAINT UNIQUE_SHELL_MAPPING_ORIGINATING_MAPPING
UNIQUE (SHELL_CASE_TYPE_ID,
        SHELL_CASE_FIELD_NAME,
        ORIGINATING_CASE_TYPE_ID,
        ORIGINATING_CASE_FIELD_NAME);
