DROP TABLE IF EXISTS public.reindex CASCADE;

--
-- Name: reindex; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.reindex (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time     TIMESTAMP NOT NULL,
    end_time       TIMESTAMP NOT NULL,
    status         VARCHAR(50) NOT NULL,
    case_type_id   INTEGER NOT NULL,
    jurisdiction   VARCHAR(70) NOT NULL,
    message        VARCHAR(200),
    CONSTRAINT fk_reindex_case_type_id FOREIGN KEY (case_type_id) REFERENCES public.case_type(id) ON DELETE CASCADE
);