DROP TABLE IF EXISTS public.reindex CASCADE;

--
-- Name: reindex; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.reindex (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reindex                  BOOLEAN NOT NULL,
    delete_old_index         BOOLEAN NOT NULL,
    case_type				 VARCHAR(70) NOT NULL,
    jurisdiction             VARCHAR(70) NOT NULL,
    index_name               VARCHAR(200) NOT NULL,
    start_time               TIMESTAMP NOT NULL,
    end_time                 TIMESTAMP,
    status                   VARCHAR(50),
    exception_message        TEXT,
    reindex_response		 TEXT
);

-- add index on case_type (used in queries like findByCaseType)
CREATE INDEX idx_reindex_case_type ON public.reindex(case_type);

-- add index on index_name (used in queries like findByIndexName)
CREATE INDEX idx_reindex_index_name ON public.reindex(index_name);