name: Publish Swagger Specs
on:
  push:
    branches:
      - master
      - RDM-10747

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Run Swagger Publisher
        run: ./gradlew application:test --tests uk.gov.hmcts.net.ccd.definition.store.SwaggerGeneratorTest
      - name: Commit to repository
        run: |
          mkdir swagger-staging
          cd swagger-staging
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub action"
          git remote add upstream "https://jenkins-reform-hmcts:${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}@github.com/hmcts/cnp-api-docs.git"
          git pull upstream master
          repo=`echo "$GITHUB_REPOSITORY" | cut -f2- -d/`
          echo "$(cat /tmp/swagger-specs.json)" > "docs/specs/$repo.json"
          git add "docs/specs/$repo.json"
          # Only commit and push if we have changes.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update spec for $repo#${GITHUB_SHA:7}"; git push --set-upstream upstream master)
